[workspace]
members = ["config", "config-derive", "errors", "id", "instruments"]
resolver = "2"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1"
base32 = "0.5"
chrono = "0.4"
colored = "2.1"
config-driver = { package = "config", version = "0.14" }
darling = "0.20"
http = "1.1"
opentelemetry = "0.27"
opentelemetry_sdk = "0.27"
opentelemetry-appender-tracing = "0.27"
opentelemetry-otlp = "0.27"
opentelemetry-semantic-conventions = "0.27"
opentelemetry-stdout = "0.27"
paste = "1.0"
percent-encoding = "2.3"
quote = "1.0"
serde = "1.0"
syn = "2.0"
thiserror = "1.0"
tokio = { version = "1.37", features = ["macros", "rt-multi-thread"] }
tower-http = "0.6"
tracing = "0.1.28"
tracing-opentelemetry = "0.28"
tracing-subscriber = "0.3"
uuid = { features = ["v7"], version = "1.11" }

# Internal dependencies
config = { path = "config" }
config-derive = { path = "config-derive" }
errors = { path = "errors" }
instruments = { path = "instruments" }

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }

missing_const_for_fn = "allow"
missing_errors_doc = "allow"
missing_panics_doc = "allow"
