[package]
name = "id"
version = "0.1.0"
edition = "2021"

[features]
serde = ["dep:serde"]
sqlx = ["dep:sqlx"]

[dependencies]
serde = { optional = true, workspace = true }
sqlx = { optional = true, workspace = true }
thiserror = { workspace = true }
uuid = { features = ["v4", "v7"], workspace = true }

# Internal dependencies
errors = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }

[lints]
workspace = true
